steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'verify']
    dir: '.'
  - id: 'tf init'
    name: 'hashicorp/terraform:0.12.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd environments/dev
        terraform init

  - id: 'tf plan'
    name: 'hashicorp/terraform:0.12.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd environments/dev
        terraform plan

  - id: 'tf apply'
    name: 'hashicorp/terraform:0.12.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd environments/dev
        terraform apply -auto-approve
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'hello-function', '--trigger-http', '--runtime', 'java11', '--entry-point', 'com.pyruby.cloudfunc.HelloWorld']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'stream-function', '--trigger-bucket=inbound-feed-bucket', '--runtime', 'java11', '--entry-point', 'com.pyruby.cloudfunc.StreamFromBucket']