steps:
  - id: 'build'
    name: 'gradle:6.5.1-jdk11'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gradle clean build
        retval=$?
        if [ $retval -ne 0 ]; then
          touch build_failed
        fi
    dir: '.'
  - id: 'save test results'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd build/reports/tests
        gsutil cp -r test gs://ons-build-artifacts/results/$BUILD_ID
        cd ../../..
        if [ -f "build_failed" ]; then rm build_failed; exit 1; fi

  - id: 'tf init'
    name: 'hashicorp/terraform:0.12.28'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd infra/environments/dev
        terraform init

  - id: 'tf plan'
    name: 'hashicorp/terraform:0.12.28'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd infra/environments/dev
        terraform plan

  - id: 'tf apply'
    name: 'hashicorp/terraform:0.12.28'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd infra/environments/dev
        terraform apply -auto-approve
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: './build/deployable'
    args: ['functions', 'deploy', 'hello-function', '--trigger-http', '--runtime', 'java11', '--entry-point', 'com.pyruby.cloudfunc.HelloWorld']
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: './build/deployable'
    args: ['functions', 'deploy', 'stream-function', '--trigger-bucket=inbound-feed-bucket', '--runtime', 'java11', '--entry-point', 'com.pyruby.cloudfunc.StreamFromBucket']
